In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("day_9/50_Startups.csv")
data.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   R&D Spend        50 non-null     float64
 1   Administration   50 non-null     float64
 2   Marketing Spend  50 non-null     float64
 3   State            50 non-null     object 
 4   Profit           50 non-null     float64
dtypes: float64(4), object(1)
memory usage: 2.1+ KB


In [4]:
data.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'State', 'Profit'], dtype='object')

In [5]:
data.State.unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [15]:
feature = data.iloc[:,[0,1,2,3]].values
print(feature.ndim)
print(feature.shape)
label = data.iloc[:,[4]].values
print(label.ndim)
print(label.shape)

2
(50, 4)
2
(50, 1)


In [16]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [17]:
feature[:,3]

array(['New York', 'California', 'Florida', 'New York', 'Florida',
       'New York', 'California', 'Florida', 'New York', 'California',
       'Florida', 'California', 'Florida', 'California', 'Florida',
       'New York', 'California', 'New York', 'Florida', 'New York',
       'California', 'New York', 'Florida', 'Florida', 'New York',
       'California', 'Florida', 'New York', 'Florida', 'New York',
       'Florida', 'New York', 'California', 'Florida', 'California',
       'New York', 'Florida', 'California', 'New York', 'California',
       'California', 'Florida', 'California', 'New York', 'California',
       'New York', 'Florida', 'California', 'New York', 'California'],
      dtype=object)

In [18]:
StateL = LabelEncoder()
StateL.fit(feature[:,3])

LabelEncoder()

In [20]:
feature[:,3] =  StateL.transform(feature[:,3])

In [24]:
feature[:5,:]

array([[165349.2, 136897.8, 471784.1, 2],
       [162597.7, 151377.59, 443898.53, 0],
       [153441.51, 101145.55, 407934.54, 1],
       [144372.41, 118671.85, 383199.62, 2],
       [142107.34, 91391.77, 366168.42, 1]], dtype=object)

In [ ]:
#k
#array(['New York', 'California', 'Florida'], dtype=object)
# array([     2,             0,          1])

In [26]:
?ColumnTransformer

In [28]:
StateOHE = ColumnTransformer([('feature',OneHotEncoder(),[3])], remainder="passthrough")
StateOHE.fit_transform(feature)
#StateOHE.transform(feature)

array([[0.0, 0.0, 1.0, 165349.2, 136897.8, 471784.1],
       [1.0, 0.0, 0.0, 162597.7, 151377.59, 443898.53],
       [0.0, 1.0, 0.0, 153441.51, 101145.55, 407934.54],
       [0.0, 0.0, 1.0, 144372.41, 118671.85, 383199.62],
       [0.0, 1.0, 0.0, 142107.34, 91391.77, 366168.42],
       [0.0, 0.0, 1.0, 131876.9, 99814.71, 362861.36],
       [1.0, 0.0, 0.0, 134615.46, 147198.87, 127716.82],
       [0.0, 1.0, 0.0, 130298.13, 145530.06, 323876.68],
       [0.0, 0.0, 1.0, 120542.52, 148718.95, 311613.29],
       [1.0, 0.0, 0.0, 123334.88, 108679.17, 304981.62],
       [0.0, 1.0, 0.0, 101913.08, 110594.11, 229160.95],
       [1.0, 0.0, 0.0, 100671.96, 91790.61, 249744.55],
       [0.0, 1.0, 0.0, 93863.75, 127320.38, 249839.44],
       [1.0, 0.0, 0.0, 91992.39, 135495.07, 252664.93],
       [0.0, 1.0, 0.0, 119943.24, 156547.42, 256512.92],
       [0.0, 0.0, 1.0, 114523.61, 122616.84, 261776.23],
       [1.0, 0.0, 0.0, 78013.11, 121597.55, 264346.06],
       [0.0, 0.0, 1.0, 94657.16, 145077.58

In [33]:
len(data)

50

In [36]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
for randomState in range(len(data)):
    X_train,X_test,y_train,y_test = train_test_split(feature,label,test_size=0.2,random_state=randomState)

    model = LinearRegression()
    model.fit(X_train,y_train)
    trainScore =  model.score(X_train,y_train)
    testScore = model.score(X_test,y_test)

    if testScore > trainScore:
        print(" train score is : {} and test score is : {} and random_state is: {}".format(trainScore,testScore,randomState))


 train score is : 0.9424153873982085 and test score is : 0.9649827631091706 and random_state is: 1
 train score is : 0.939738573687705 and test score is : 0.9794557471168575 and random_state is: 2
 train score is : 0.9473550252395463 and test score is : 0.956230953700171 and random_state is: 4
 train score is : 0.9438480769998759 and test score is : 0.9670002673417639 and random_state is: 5
 train score is : 0.938444506943968 and test score is : 0.9908827024290412 and random_state is: 10
 train score is : 0.9485818181379404 and test score is : 0.9492627421151756 and random_state is: 12
 train score is : 0.9410732833942711 and test score is : 0.9729554629392217 and random_state is: 14
 train score is : 0.9458045483432699 and test score is : 0.9658084012928773 and random_state is: 21
 train score is : 0.9424901430407254 and test score is : 0.9765041430321745 and random_state is: 22
 train score is : 0.946469967650758 and test score is : 0.9689809000692785 and random_state is: 24
 train s

In [37]:
X_train,X_test,y_train,y_test = train_test_split(feature,label,test_size=0.2,random_state=10)

model = LinearRegression()
model.fit(X_train,y_train)
trainScore =  model.score(X_train,y_train)
testScore = model.score(X_test,y_test)

In [38]:
print(model.score(X_train,y_train))
print(model.score(X_test,y_test))

0.938444506943968
0.9908827024290412


In [61]:
import pickle
pickle.dump(model,open('ProfitPredictor.model','wb'))

In [ ]:
Enter R&D Spend: 1232
Enter admSpend: 234
Enter markSpend: 345

    #array(['New York', 'California', 'Florida'], dtype=object)
# array([     2,             0,          1])

In [55]:
#User Interaction
rdSpend = float(input("Enter R&D Spend: "))
admSpend = float(input("Enter Admin Spend: "))
markSpend = float(input("Enter Marketing Spend: "))

state = input("Enter State: ")

Enter R&D Spend: 1234
Enter Admin Spend: 345
Enter Marketing Spend: 456
Enter State: California


In [56]:
featureArray =  np.array([[rdSpend,admSpend,markSpend,state]])
featureArray

array([['1234.0', '345.0', '456.0', 'California']], dtype='<U32')

In [57]:
featureArray[:,3] = StateL.transform(featureArray[:,3])
featureArray

array([['1234.0', '345.0', '456.0', '0']], dtype='<U32')

In [58]:
StateOHE.fit_transform(featureArray)

array([['1.0', '1234.0', '345.0', '456.0']], dtype='<U32')

In [59]:
featureArray = featureArray.astype('object') 

In [60]:
model.predict(featureArray)

array([[51306.97121533]])